image: python:3.12-alpine

run_tests:
  stage: test
  script:
  - apk add proj proj-dev proj-util gcc musl-dev tzdata gdal gdal-dev g++
  - ln -sf /usr/share/zoneinfo/Europe/Prague /etc/localtime
  - pip install pytest
  - pip install -r requirements.txt
  - python3 -m pytest tests/test_reader_log.py tests/test_reader_ers.py

build_pages:
  stage: test
  script:
  - apk add pandoc
  - pip install -r docs/requirements.txt
  - (cd docs; sphinx-build -b html source ../public)
  only:
  - branches
  except:
  - master

pages:
  stage: deploy
  script:
  - apk add pandoc    
  - pip install -r docs/requirements.txt
  - (cd docs; sphinx-build -b html source ../public)
  artifacts:
    paths:
    - public
  only:
  - master
